[sites_db.hosts.sites_db]
# slaves=["127.0.0.1","127.0.0.1"] # ip для слэйв серверов.
[sites_db.vars]
ansible_ssh_host="192.168.80.130"
ansible_ssh_user="root"
db_name="dev"
db_user="dev"
db_user_password="testpartner_db"
