--- 

- name: Create inventory files
  hosts: localhost
  pre_tasks:
    - name: Create inventory file
      template:
        src: ./inventori.ini
        dest: /home/nicki/ansimble-test/inventory
  tags:
    - create_inv

- name: Create db and configure
  hosts: mysql_db_mains
  roles:
    - install_mysql
  tags:
    - install_mysql